---
services:
  palworld:
    image: thijsvanloef/palworld-server-docker:v0.38.1
    restart: unless-stopped
    container_name: palworld-server
    stop_grace_period: 600s  # Set to however long you are willing to wait for the container to gracefully stop
    ports:
      - 8211:8211/udp
      - 27015:27015/udp  # Required if you want your server to show up in the community servers tab
      # - 8212:8212/tcp  # Port for REST API if REST_API_ENABLED: true
    environment:
      PUID: 1000
      PGID: 1000
      PORT: 8211  # Optional but recommended
      PLAYERS: 16  # Optional but recommended
      SERVER_PASSWORD: "XXXXX"  # Optional but recommended
      MULTITHREADING: true
      RCON_ENABLED: true
      RCON_PORT: 25575
      BUILD_OBJECT_DAMAGE_RATE: 0 # 非據點結構損壞率
      BUILD_OBJECT_DETERIORATION_DAMAGE_RATE: 0 # 非據點結構損壞率
      DEATH_PENALTY: "None" # 無死亡懲罰
      BASE_CAMP_WORKER_MAX_NUM: 20 # 單據點工人最大數量
      PAL_EGG_DEFAULT_HATCHING_TIME: 0 # 孵蛋時間
      TZ: "Asia/Taipei"
      ADMIN_PASSWORD: "XXXXX"
      COMMUNITY: true  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
      SERVER_NAME: "tomorrow"
      SERVER_DESCRIPTION: "tomorrow"
      ALLOW_CONNECT_PLATFORM: "Steam" # Defaults to "Steam" if not set, set this to "Xbox" if you want to host a server for Xbox players. CROSSPLAY BETWEEN XBOX-STEAM IS NOT YET SUPPORTED
    volumes:
      - ./palworld:/palworld/
